### ISSUE TITLE
Wrong shebang notation

### ISSUE THREAD

**Issue by ktagen-sudo** [UNM-CARC/QuickBytes#112]
For the Quickbyte "QuickBytes/GNU Parallel.md" 

the shebang notation that is used under the "Code for PBS script" section 
appears to be "#/bin/bash" but I think it should be "#!/bin/bash"

**Comment by gmfricke** [comment]
@ktagen-sudo Sounds right. Can you create a pull request?

**Comment by ktagen-sudo** [comment]
@gmfricke Absolutely. I will do that
