### ISSUE TITLE
Add Jupyterhub User Env Requirement

### ISSUE THREAD

**Issue by gmfricke** [UNM-CARC/QuickBytes#40]
To see user home dir conda environments in jupyterhub the user has to install the appropriate kernel into that environment. 

eg. 

```
source activate nlp
conda install ipykernel
```
![nlp-grab](https://user-images.githubusercontent.com/3946771/72004330-6262f100-3208-11ea-823f-a85d8e60cd55.png)

**Comment by akrausfish** [comment]
Done with pull request #60
