### ISSUE TITLE
Write Orca Quickbyte

### ISSUE THREAD

**Issue by gmfricke** [UNM-CARC/QuickBytes#71]
We should include a slurm and pbs version. Discuss MPI and NBO.

#!/usr/bin/bash

#PBS -n orca_nbo_test
#PBS -o test.out
#PBS -l walltime=00:10:00
#PBS -l nodes=2:ppn=8
#PBS -M mfricke@unm.edu
#PBS -m bae

input_file=nbo_bpy-Pt-ditBucat.inp

cd $PBS_O_WORKDIR

module load orca/4.0.0/openmpi/2.0.2
module load nbo/7/pgi-16.3

# Orca needs the full path when running in parallel
full_orca_path=$(which orca)

$full_orca_path $input_file

**Comment by liphardt** [comment]
Addressed with pull request #73
